name: local_auth
description: Flutter plugin for Android and iOS devices to allow local
  authentication via fingerprint, touch ID, face ID, passcode, pin, or pattern.
repository: https://github.com/flutter/plugins/tree/main/packages/local_auth/local_auth
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+local_auth%22
version: 2.1.1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: local_auth_android
      ios:
        default_package: local_auth_ios
      windows:
        default_package: local_auth_windows

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  local_auth_android:
    git:
      url: https://github.com/iouring-engineering/flutter-local_auth.git
      path: local_auth_android
      ref: develop
  local_auth_ios:
    git:
      url: https://github.com/iouring-engineering/flutter-local_auth.git
      path: local_auth_ios
      ref: develop
  local_auth_platform_interface:
    git:
      url: https://github.com/iouring-engineering/flutter-local_auth.git
      path: local_auth_platform_interface
      ref: develop
  local_auth_windows:
    git:
      url: https://github.com/iouring-engineering/flutter-local_auth.git
      path: local_auth_windows
      ref: develop

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.1.0
  plugin_platform_interface: ^2.1.2
