name: local_auth_ios
description: iOS implementation of the local_auth plugin.
repository: https://github.com/flutter/plugins/tree/master/packages/local_auth/local_auth_ios
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+local_auth%22
version: 1.0.6
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: local_auth
    platforms:
      ios:
        pluginClass: FLTLocalAuthPlugin
        dartPluginClass: LocalAuthIOS

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  local_auth_platform_interface:
    git:
      url: git@github.com:iouring-engineering/flutter-local_auth.git
      path: local_auth_platform_interface
      ref: develop

dev_dependencies:
  flutter_test:
    sdk: flutter
